/* eslint-disable react/jsx-no-undef */
import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import Slider from  '../components/slider';




// const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Project Exhibition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {/* <div className="container h-40 bg-red-400" ></div> */}

        <Slider/>
      </main>
    </>
  )
}